version: "3"
services:
  app:
    build: .
    command: make test
    environment:
      - SHELL=/bin/sh
      - PORT=3100
    ports:
      - 3100:3100
    volumes:
      - ./jsonHttpHandler/:/go/src/app/jsonHttpHandler/
      - ./examples/:/go/src/app/examples/
      - ./test/:/go/src/app/test/
      - ./Makefile:/go/src/app/Makefile

